# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: setup-bob
description: Setup GitHub CLI, bob, on GitHub Actions runners
inputs:
  github-token:
    description: "GitHub token to access the bob release."
    required: true
  tag:
    description: "Release tag of bob CLI to install; install the latest release by default"
    required: false
    # empty for the latest release
    default: ''
outputs:
  installed_version:
    description: "The installed version as reported by the tool"
    value: ${{ steps.capture.outputs.installed_version }}

runs:
  using: composite
  steps:
    - name: Fetch release artifact
      uses: jaxxstorm/action-install-gh-release@7f2440a9a41f74262d8f6433da138c799799a969 # v1.13.0
      with:
        repo: hashicorp/bob
        tag: ${{ inputs.tag }}
        token: ${{ inputs.github-token }}
        cache: false

    - name: Capture installed version
      id: capture
      shell: bash
      run: |
        echo "installed_version=$(bob -version)" | tee -a "$GITHUB_OUTPUT"
