name: CI
on:
  push:

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run:  npm test ./bob.test.js
